name: Android CI

on:
  push:
    branches:
      - feature/add_workflows
  pull_request:
    branches:
      - feature/add_workflows

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup JDK 
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # O 'zulu' según tu preferencia
          java-version: '17' 

      # Install Android SDK 
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
            
      # Get API key 
      - name: Set up OpenAI API Key
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} 
        run: echo "API key is set."          

      # Compile
      - name: Build with Gradle
        run: ./gradlew build

      # Store APK artifact
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: app/build/outputs/apk/debug/CapsuleScanner-debug.apk        
