name: Android CI

on:
  push:
    branches:
      - feature/add_workflows
  pull_request:
    branches:
      - feature/add_workflows

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup JDK 
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # O 'zulu' según tu preferencia
          java-version: '17' 

      # Install Android SDK 
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
            
      # Build with Gradle 
      - name: Build with Gradle
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: ./gradlew assembleDebug 
      
      # Save APK to Github Artifacts 
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          
      - name: upload apk to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID_RELEASE}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          file: app/build/outputs/apk/debug/app-debug.apk      

