name: Test Workflow

#Trigger when pushing to specific branch
on:
  push:
    branches:
      - feature/add_workflows

jobs:
  first-run:
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Simple Task
        run: echo "Hello, this is a test run!"

      - name: List repository files
        run: ls -la
